#!/bin/bash

countries=(Albania Greece Portugal Argentina Hong_Kong Romania Australia Hungary Serbia Austria Iceland Singapore Belgium India Slovakia Bosnia_And_Herzegovina Indonesia Slovenia Brazil Ireland South_Africa Bulgaria Israel South_Korea Canada Italy Spain Chile Japan Sweden Costa_Rica Latvia Switzerland Croatia Luxembourg Taiwan Cyprus Malaysia Thailand Czech_Republic Mexico Turkey Denmark Moldova Ukraine Estonia Netherlands United_Kingdom Finland New_Zealand United_States France North_Macedonia Vietnam Georgia Norway Germany Poland)

RANDOM=$$$(date +%s)

read -p "Enter time to switch in seconds: " time

while true
do
	# Get random expression...
	randomcountries=${countries[$RANDOM % ${#countries[@]} ]}
	nordvpn connect $randomcountries
	echo "Press [CTRL+C] to stop.."
	sleep $time
done
